

INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(6,'地图','/widgets/map.html');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(7,'时钟','/widgets/clock.html');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(8,'私信','/rs/msg/widget/msg');

INSERT INTO PORTAL_ITEM(ID,NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(6,'私信',2,3,1,8);

